# Generated by Django 4.2.6 on 2023-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
