# Generated by Django 4.2.6 on 2023-11-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspotter', '0002_alter_studyspot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
