# Generated by Django 4.2.6 on 2023-11-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspotter', '0002_alter_studyspot_id'),
        ('studyspotter', '0002_studyspot_food'),
    ]

    operations = [
    ]
