# Generated by Django 4.2.6 on 2023-11-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspotter', '0003_merge_0002_alter_studyspot_id_0002_studyspot_food'),
        ('studyspotter', '0003_studyspot_rejection_reason'),
    ]

    operations = [
    ]
