# Generated by Django 4.2.6 on 2023-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspotter', '0005_alter_studyspot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
